---
# Default state for all rules
default: true

# MD003/heading-style/header-style - Heading style
MD003:
  style: "atx"

# MD004/ul-style - Unordered list style
MD004:
  style: "dash"

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 4

# MD013/line-length - Line length
MD013:
  code_blocks: false
  tables: false
  line_length: 120

# MD035/hr-style - Horizontal rule style
MD035:
  style: "---"

MD033: false
