FROM radare/radare2@sha256:baee52409681d24a2f6c9c324b92f3c8c67412cc8fe13f06ab4ab0a26cf57c6b

COPY internal/ /home/r2/input_vectors/

ENTRYPOINT [ "python3", "/home/r2/input_vectors/input_vectors_r2.py" ]
