# This is a working example configuration for FACT
# Options that have a default value are commented out with their default set.
[common]
# temp-dir-path = "/tmp"

# Directory that will be used to share data from the host to docker containers
# Permissions have to be 0o770 and the group has to be 'docker'.
# Will be created if it does not exist
docker-mount-base-dir = "/tmp/fact-docker-mount-base-dir"

[common.redis]
fact-db = 3
test-db = 13
host = "localhost"
port = 6379
# Set the password for redis here if you have AUTH enabled
# password =

[common.logging]
# level = "WARNING"
# file_backend = "/tmp/fact_backend.log"
# file_frontend = "/tmp/fact_frontend.log"
# file_database = "/tmp/fact_database.log"


[common.postgres]
server = "localhost"
port = 5432
database = "fact_db"
test-database = "fact_test"
ro-user = "fact_user_ro"
ro-pw = "change_me_ro"
rw-user = "fact_user_rw"
rw-pw = "change_me_rw"
del-user = "fact_user_del"
del-pw = "change_me_del"
admin-user = "fact_admin"
admin-pw = "change_me_admin"

# Defines analysis presets as shown in the frontend
# You can add as many as you like
[[common.analysis_preset]]
name = "default"
# choose preselected plugins
plugins = [
    "cpu_architecture",
    "crypto_material",
    "cve_lookup",
    "exploit_mitigations",
    "known_vulnerabilities",
    "software_components",
    "users_and_passwords",
]

[[common.analysis_preset]]
name = "minimal"
plugins = []

[backend]
firmware-file-storage-directory = "/media/data/fact_fw_data"
block-delay = 0.1
ssdeep-ignore = 1
intercom-poll-delay = 1.0
analysis-status-update-interval = 4.5
scheduling-worker-count = 4
collector-worker-count = 2
throw-exceptions = false


[backend.plugin-defaults]
# Default number of processes for plugins.
# Can be overwritten by setting backend.plugin.processes
processes = 2

[backend.unpacking]
processes = 4
# file types in whitelist are not extracted
whitelist = [
    "application/x-object",
    "application/x-shockwave-flash",
    "audio/mpeg",
    "image/gif",
    "image/jpeg",
    "image/png",
    "text/plain",
    "video/mp4",
    "video/mpeg",
    "video/ogg",
    "video/quicktime",
    "video/x-msvideo",
]
# extract until this layer
max-depth = 8
# Memory limit in MiB.
# memory-limit = 2048
throttle-limit = 100
# tcp port(s) for task server
base-port = 9900
# if you experience FileNotFound errors during unpacking, increasing this value slightly might help
delay = 0.0
# the extractor runs containerized using this image/tag
docker-image = "fkiecad/fact_extractor:latest"

[backend.binary-search]
# maximum number of matching strings stored per match
max-strings-per-match = 10


[[backend.plugin]]
name = "cpu_architecture"
processes = 4

[[backend.plugin]]
name = "cve_lookup"
processes = 4
# CVE scores greater or equal to this value are shown as "critical"
min-critical-score = 9.0
# match CVE entries without versions constraints (`false` by default due to the high risk of false positives)
match-any = false

[[backend.plugin]]
name = "cwe_checker"
processes = 2
memory-limit = "4G"
# see https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details
# unintuitively, if memswap-limit is set to the same value as memory-limit, the swap will *not* be used
memswap-limit = "4G"

[[backend.plugin]]
name = "elf_analysis"
processes = 4

[[backend.plugin]]
name = "exploit_mitigations"
processes = 4

[[backend.plugin]]
name = "file_hashes"
hashes = [
    "md5",
    "sha1",
    "sha256",
    "sha512",
    "ripemd160",
    "whirlpool",
]

[[backend.plugin]]
name = "input_vectors"
processes = 4

[[backend.plugin]]
name = "kernel_config"
processes = 4

[[backend.plugin]]
name = "printable_strings"
min-length = 6

[[backend.plugin]]
name = "users_and_passwords"
processes = 4



[frontend]
results-per-page = 10
# number-of-latest-firmwares-to-display = 10
ajax-stats-reload-time = 10000
# max-elements-per-chart = 10

# This is used in redirecting to the radare web service.
# If you use our nginx config this must be set to "https://localhost/radare"
# otherwise it must be set to "http://localhost:8000"
radare2-url = "http://localhost:8000"
# communication-timeout = 60


[frontend.authentication]
enabled = false
user-database = "sqlite:////media/data/fact_auth_data/fact_users.db"
password-salt = "5up3r5tr0n6_p455w0rd_5417"


[frontend.hasura]
admin-secret = "4dM1n_S3cR3T_changemeplz"
