name: Deploy Docs to github pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    # check out repository
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: install deps
      run: |
        python3 -m pip install --upgrade pip wheel setuptools
        python3 -m pip install -r ./docsrc/doc_dependencies.txt

    - name: Build Docs
      run: |
        make -C docsrc html
        touch ./docsrc/_build/html/.nojekyll

    - name: Deploy Docs to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docsrc/_build/html
